domain: my-site.github.io
url: https://my-site.github.io

title: left-alert-chaos
tagline: a place on the internet that happens to have my thoughts and projects
description: My personal page.

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one